backend:
  name: github
  repo: quentinglorieux/leishman # Path to your GitHub repository

media_folder: static/img
public_folder: images

collections:
  - label: "Events"
    name: "events"
    files:
      - label: "About Page"
        name: "about"
        file: "data/events_decap.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}
          - {label: Location, name: location, widget: string}
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            default: ""
            media_library:
              config:
                multiple: false
