backend:
  name: github
  repo: quentinglorieux/leishman # Path to your GitHub repository

media_folder: static/img
public_folder: images

collections:
  - label: Members
    name: members
    folder: nuxt-app/public/data/members
    create: true
    identifier_field: lastname
    fields:
      - { label: "Nom", name: "lastname", widget: "string", required: true }
      - { label: "Prénom", name: "firstname", widget: "string", required: true }
      - {
          label: "Laboratoire",
          name: "laboratory",
          widget: "string",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Activités",
          name: "activities",
          widget: "markdown",
          required: false,
        }
