media: pagescms/media
content:
  - name: events_home
    label: Events HomeJSON file
    type: file
    path: "nuxt-app/public/data/events_home.json"
    view:
      fields: [title, type, date, description, image]
    fields:
      - name: title
        label: Title
        type: string
      - name: type
        label: Type
        type: select
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: image
      - name: description
        label: Description
        type: rich-text
  - name: events_home
    label: Events HomeJSON collection
    type: file
    path: "nuxt-app/public/data/events_home_coll.json"
    view:
      fields: [title, type, date, description, image]
    fields:
      - name: title
        label: Title
        type: string
      - name: type
        label: Type
        type: select
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: image
      - name: description
        label: Description
        type: rich-text
  - name: members
    label: Members
    type: collection
    path: "pagescms/_members"
    view:
      fields: [lastname, firstname, laboratory, activities]
    fields:
      - name: lastname
        label: Lastname
        type: string
      - name: firstname
        label: Firstname
        type: string
      - name: laboratory
        label: Laboratory
        type: string
      - name: activities
        label: Activities
        type: rich-text
  - name: laboratories
    label: Laboratories
    type: collection
    path: "pagescms/_labo"
    view:
      fields: [name, GPS, head, logo, description]
    fields:
      - name: name
        label: Name
        type: string
      - name: GPS
        label: GPS
        type: number
      - name: logo
        label: Logo
        type: image
      - name: description
        label: Description
        type: rich-text
  - name: events
    label: Events
    type: collection
    path: "pagescms/_event"
    view:
      fields: [title, type, date, description, image]
    fields:
      - name: title
        label: Title
        type: string
      - name: type
        label: Type
        type: select
        options:
          values: [seminar, meeting, publication]
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: image
      - name: description
        label: Description
        type: rich-text
  - name: aboutUs
    label: About Us
    type: file
    path: "pagescms/about.md"
    fields:
      - name: title1
        label: Title1
        type: string
      - name: paragraph1
        label: Paragraph1
        type: rich-text
      - name: title2
        label: Title2
        type: string
      - name: paragraph2
        label: Paragraph2
        type: rich-text
      - name: title3
        label: Title3
        type: string
      - name: paragraph3
        label: Paragraph3
        type: rich-text
      - name: title4
        label: Title4
        type: string
      - name: paragraph4
        label: Paragraph4
        type: rich-text
