backend:
  name: github
  repo: quentinglorieux/leishman # Path to your GitHub repository
  # base_url: https://orcid-sveltia.quentin-glorieux.workers.dev  # Your Cloudflare Worker
  commit_messages:
    create: Create - {{collection}} “{{slug}}”
    update: Update - {{collection}} “{{slug}}”
    delete: Delete - {{collection}} “{{slug}}”
    uploadMedia: Upload - “{{path}}”
    deleteMedia: Delete - “{{path}}”
    openAuthoring: "{{message}}"
  automatic_deployments: true

media_folder: nuxt-app/public/images
public_folder: /assets/images
show_preview_links: false
superadmin: true
# editor:
#   preview: true

collections:
  - label: Documents
    name: documents
    icon: description
    folder: nuxt-app/content/documents
    media_folder: /nuxt-app/public/assets/documents 
    public_folder: /assets/documents
    create: true
    identifier_field: title
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "File",
          name: "file",
          widget: "file",
          required: true,
        }
  - label: Users
    name: users
    icon: group
    create: true
    identifier_field: lastname
    files:
      - label: "Admin"
        name: "admin"
        file: "nuxt-app/public/data/users/admin.yml"
        fields:
          - label: "Admin"
            name: "admin_list"
            widget: "list"
            fields:
              - { label: "Nom", name: "lastname", widget: "string", required: true }
              - { label: "Prénom", name: "firstname", widget: "string", required: false }
              - { label: "Email", name: "email", widget: "string", required: false }
              - { label: "ORCID", name: "orcid", widget: "string", required: true }
      - label: "Editor"
        name: "editor"
        file: "nuxt-app/public/data/users/editor.yml"
        fields:
          - label: "Editor"
            name: "editor_list"
            widget: "list"
            fields:
              - { label: "Nom", name: "lastname", widget: "string", required: true }
              - { label: "Prénom", name: "firstname", widget: "string", required: false }
              - { label: "Email", name: "email", widget: "string", required: false }
              - { label: "ORCID", name: "orcid", widget: "string", required: true }
      - label: "Viewer"
        name: "viewer"
        file: "nuxt-app/public/data/users/viewer.yml"
        fields:
          - label: "Viewer"
            name: "viewer_list"
            widget: "list"
            fields:
              - { label: "Nom", name: "lastname", widget: "string", required: true }
              - { label: "Prénom", name: "firstname", widget: "string", required: false }
              - { label: "Email", name: "email", widget: "string", required: false }
              - { label: "ORCID", name: "orcid", widget: "string", required: true }