[build]
  # The base directory where the Nuxt.js app is located
  base = "nuxt-app"
  publish = "dist"  # The directory to publish
  command = "npm run build"  # The build command

# Redirects and headers can be defined here if needed
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
